# Generated by Django 5.0.7 on 2024-07-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('century', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decades', to='nost.century')),
            ],
        ),
    ]
