# Generated by Django 5.0.7 on 2024-07-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nost', '0002_decade'),
    ]

    operations = [
        migrations.AddField(
            model_name='decade',
            name='end_year',
            field=models.CharField(default='no end', max_length=100),
        ),
        migrations.AddField(
            model_name='decade',
            name='name',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AddField(
            model_name='decade',
            name='start_year',
            field=models.CharField(default='no start', max_length=100),
        ),
    ]
